// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqegelgkfcogijmecxqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZWdlbGdrZmNvZ2lqbWVjeHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTM1MTIsImV4cCI6MjA2ODU2OTUxMn0.3hvrEGRJldFhsJX5ITbagFzFAW33I82Jjkt_4yGLRZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});